"""
Auto-generated Python code
Scenario : Data Analysis
Prompt   : response_002.txt
Run      : 2
"""

# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

# Define placeholder marketing campaign data
data = {
    'Campaign ID': [1, 2, 3, 4, 5],
    'Impressions': [1000, 1200, 1500, 1800, 2000],  # Number of times the ad was displayed
    'Clicks': [50, 60, 70, 80, 90],  # Number of times the ad was clicked
    'Conversions': [20, 25, 30, 35, 40],  # Number of successful sales or leads
    'Cost': [100, 120, 150, 180, 200],  # Cost of the campaign
    'Revenue': [500, 600, 700, 800, 900]  # Revenue generated by the campaign
}

# Create a Pandas DataFrame from the data
df = pd.DataFrame(data)

# Calculate conversion rate (number of conversions divided by number of clicks)
df['Conversion Rate'] = df['Conversions'] / df['Clicks'] * 100

# Calculate return on investment (ROI)
df['ROI'] = (df['Revenue'] - df['Cost']) / df['Cost'] * 100

# Calculate customer engagement (number of clicks divided by impressions)
df['Customer Engagement'] = df['Clicks'] / df['Impressions'] * 100

# Print the updated DataFrame
print(df)

# Define a function to calculate KPIs for a single campaign
def calculate_kpis(campaign_id):
    campaign = df[df['Campaign ID'] == campaign_id]
    if campaign.empty:
        return None  # No data found for the campaign
    conversion_rate = campaign['Conversion Rate'].values[0]
    roi = campaign['ROI'].values[0]
    customer_engagement = campaign['Customer Engagement'].values[0]
    return conversion_rate, roi, customer_engagement

# Test the function
campaign_id = 3
kpi_values = calculate_kpis(campaign_id)
if kpi_values:
    print(f'Conversion Rate for campaign {campaign_id}: {kpi_values[0]}%')
    print(f'ROI for campaign {campaign_id}: {kpi_values[1]}%')
    print(f'Customer Engagement for campaign {campaign_id}: {kpi_values[2]}%')

# Define a function to plot KPIs for all campaigns
def plot_kpis():
    plt.figure(figsize=(10, 6))
    plt.plot(df['Conversion Rate'], label='Conversion Rate')
    plt.plot(df['ROI'], label='ROI')
    plt.plot(df['Customer Engagement'], label='Customer Engagement')
    plt.xlabel('Campaign Index')
    plt.ylabel('KPI Value')
    plt.title('Marketing Campaign KPIs')
    plt.legend()
    plt.show()

# Test the function
plot_kpis()